# Generated by Django 4.1.7 on 2023-03-18 09:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='colored_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Page.file_path_colored),
        ),
    ]
